# Generated by Django 3.1.1 on 2020-11-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50, null=True)),
                ('cuantity', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField()),
                ('description', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.unit')),
            ],
        ),
    ]
