# Generated by Django 3.1.3 on 2020-11-25 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cuantity',
            new_name='quantity',
        ),
    ]
