# Generated by Django 3.1.3 on 2020-11-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_generalorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalorder',
            name='product',
        ),
        migrations.AddField(
            model_name='generalorder',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
