# Generated by Django 3.1.3 on 2020-11-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20201126_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalorder',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='warehouse.GeneralOrder'),
        ),
    ]
