# Generated by Django 3.1.3 on 2020-11-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20201127_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_quantity',
        ),
        migrations.AddField(
            model_name='generalorder',
            name='item_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
