# Generated by Django 3.1.3 on 2020-11-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20201127_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalorder',
            name='item_quantity',
        ),
        migrations.CreateModel(
            name='ItemQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.PositiveIntegerField(null=True)),
                ('order', models.ManyToManyField(blank=True, related_name='items', to='warehouse.GeneralOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.product')),
            ],
        ),
    ]
