# Generated by Django 3.1.3 on 2020-11-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20201127_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemquantity',
            name='order',
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.generalorder'),
        ),
    ]
