# Generated by Django 3.1.3 on 2020-11-29 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20201129_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquantity',
            name='item_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemquantity',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.generalorder'),
        ),
        migrations.AlterField(
            model_name='itemquantity',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.product'),
        ),
    ]
