# Generated by Django 3.1.3 on 2020-11-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_auto_20201129_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquantity',
            name='item_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
