# Generated by Django 3.1.3 on 2020-11-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_auto_20201129_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquantity',
            name='item_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemquantity',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.generalorder'),
        ),
        migrations.AlterField(
            model_name='itemquantity',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.product'),
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_id', to='warehouse.warehouse')),
                ('warehouse_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_id', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
