# Generated by Django 3.1.3 on 2020-12-02 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_auto_20201130_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_user', to='warehouse.warehouse'),
        ),
    ]
