# Generated by Django 3.1.3 on 2020-12-02 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_auto_20201202_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse'),
        ),
    ]
