# Generated by Django 3.1.3 on 2020-12-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_auto_20201204_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], default='Pending', max_length=200, null=True),
        ),
    ]
