# Generated by Django 3.1.3 on 2020-12-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_generalorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
