# Generated by Django 3.1.3 on 2020-12-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_auto_20201204_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
