# Generated by Django 3.1.3 on 2020-12-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_auto_20201205_1908'),
        ('warehouse', '0026_auto_20201205_2010'),
    ]

    operations = [
    ]
